version: '3.8'

services:
  db:
    build: ./db
    container_name: db

    restart: always
    ports:
      - "3307:3306"
    networks:
      - internal_network

  api:
    build: ./api
    container_name: api
    environment:
      DATABASE_URL: mysql://root:root@db:3306/boeri
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - internal_network

# Servicio Graphite para almacenar métricas de rendimiento
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "80:80"       # Interfaz web de Graphite (útil para verificación)
      - "2003:2003"   # Puerto para recibir datos de métricas
      - "8125:8125/udp" # Puerto para StatsD
      - "8126:8126"   # Puerto para la API de Graphite
    volumes:
      - graphite-data:/var/lib/graphite/whisper  # Persistencia para datos de Graphite
    networks:
      - internal_network


networks:
  internal_network:
    driver: bridge


volumes:
  db_data:
    driver: local
  graphite-data:
    driver: local