version: '3.8'

services:
  db:
    build: ./db
    container_name: db

    restart: always
    ports:
      - "3307:3306"
    networks:
      - internal_network

  api:
    build: ./api
    container_name: api
    environment:
      DATABASE_URL: mysql://root:root@db:3306/boeri
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - internal_network

  test:
    build: ./test
    container_name: test
    depends_on:
      - api
    volumes:
      - ./test:/app
      - ./test/reports:/tmp/artifacts  
    networks:
      - internal_network




networks:
  internal_network:
    driver: bridge


volumes:
  db_data:
    driver: local
